### ISSUE TITLE
HacktoberFest 2020 

### ISSUE THREAD

**Issue by TraXIcoN** [TraXIcoN/FreeCodeCamp-Projects#1]
This repo welcomes all the git-GitHub newbies. Add your solutions to mini-projects or challenges provided by the freeCodeCamp 
 the curriculum in whatever language you want(The basic idea of the solution should be the same).

**Comment by yashqwerty1** [comment]
Thanks for this effort. I would like to contribute here. I just want you to provide format for solutions.

**Comment by 23krishna** [comment]
please assign

**Comment by TraXIcoN** [comment]
> Thanks for this effort. I would like to contribute here. I just want you to provide format for solutions.

I just updated the readme. There is no specific format you can send your solution in any format just make sure you add comments to your solution to explain your code..

**Comment by yashqwerty1** [comment]
Thank You. I Appreciate your help for beginners.

**Comment by TraXIcoN** [comment]
> please assign

No need anyone can post a pull request this is just for beginners to get started with git and Github

**Comment by adiksha20** [comment]
Can we implement sorting algorithms in java?

**Comment by TraXIcoN** [comment]
> Can we implement sorting algorithms in java?
> 

Yes I will add a Java folder then you can commit changes inside that folder

**Comment by Wach-E** [comment]
I added a python script that gives the period of the day to a user and also greets him/her by taking into consideration the local time of the user too #66

**Comment by Vishnurr2k01** [comment]
how can i contribute to this project?

**Comment by aritrochakraborty29** [comment]
Can you please assign me..?

**Comment by ImKeelan** [comment]
Can I be assigned please

**Comment by saranshkotnala** [comment]
bro why is no one reviewing pull requests?

**Comment by TraXIcoN** [comment]
I was busy this weekend sorry about the late action I added the hacktoberfest-accepted label so y'all will be able to see the timer on the hacktoberfest portal

> bro why is no one reviewing pull requests?

**Comment by adityaSINGHrox** [comment]
hey, 
thanks for the good work
I would like to contribute too.
