### ISSUE TITLE
Algorithms/Programs in different languages

### ISSUE THREAD

**Issue by TraXIcoN** [TraXIcoN/FreeCodeCamp-Projects#16]
Y'all can add different programs scripted by you in any language you want.
If you scripted in a language whose folder or category is not present in the repo then create one and then add.

**Comment by yashqwerty1** [comment]
Yes That's perfect I would love to this.

**Comment by AakashBelide** [comment]
I would like to contribute to this.

**Comment by Shivamishra21** [comment]
I would like to contribute to this.

**Comment by TraXIcoN** [comment]
Great!

**Comment by Rishav0907** [comment]
Can I contribute ?

**Comment by TraXIcoN** [comment]
> Can I contribute ?

Yes you can

**Comment by FaithKovi** [comment]
I want to contribute, can I ?

**Comment by amitsat27** [comment]
can i contribute ?

**Comment by amitsat27** [comment]
@TraXIcoN can i contribute?

**Comment by TraXIcoN** [comment]
Yes anyone can contribute!

**Comment by wiredfoxterrier** [comment]
Hey @TraXIcoN 

I would like to contribute to the Java section. It would be great several programs to it. I would also like to know what type of programs I could contribute to the same.
It would be great if you could assign this to me.
Thanks,
Ansh Sharma
(wiredfoxterrier)

**Comment by TraXIcoN** [comment]
> Hey @TraXIcoN
> 
> I would like to contribute to the Java section. It would be great several programs to it. I would also like to know what type of programs I could contribute to the same.
> It would be great if you could assign this to me.
> Thanks,
> Ansh Sharma
> (wiredfoxterrier)

I'll make a new issue for Java programs and then I will assign it to you @wiredfoxterrier

**Comment by yashqwerty1** [comment]
@TraXIcoN can You create the same for Python and assign it to me .

**Comment by aritrochakraborty29** [comment]
@TraXIcoN  can you please assign me.?

**Comment by TraXIcoN** [comment]
No need @aritrochakraborty29  this issue is just so that people can discover this repository

**Comment by cetinogut** [comment]
This is a great way to contribute. Many thanks.
