### ISSUE TITLE
Basic Java programs needed!

### ISSUE THREAD

**Issue by TraXIcoN** [TraXIcoN/FreeCodeCamp-Projects#61]
You can add any basic java program you want!
Just make sure they are not repeated and are properly commented 
#16

**Comment by yashqwerty1** [comment]
Ok here I'm Again. Can you assign the task?

**Comment by TraXIcoN** [comment]
@wiredfoxterrier asked for this issue first but all right I will assign this ti you as well @yashqwerty1

**Comment by TraXIcoN** [comment]
@wiredfoxterrier please give a confirmation here

**Comment by yashqwerty1** [comment]
Information like !

**Comment by wiredfoxterrier** [comment]
@TraXIcoN I have created a PR for the programs. Could you let me know if there are any changes need for the same?
