### ISSUE TITLE
Can you please add these two labels?

### ISSUE THREAD

**Issue by achoudh5** [TraXIcoN/FreeCodeCamp-Projects#80]
https://hacktoberfest.digitalocean.com/hacktoberfest-update

Hi 

Can you please add two labels:-

1. At you repo, main page-> `hacktoberfest` label

2. Closed PR's-> label->`hacktoberfest-accepted`

**Comment by osmarpetry** [comment]
Is one or other, don't need both

**Comment by achoudh5** [comment]
They mentioned:-

`A note to maintainers: Due to this change, you no longer need to opt out of Hacktoberfest. Instead, we invite you to classify your repository with the hacktoberfest topic **and** apply hacktoberfest-accepted labels to pull requests you want to accept. We’ve included a few gifs below to show you how simple this can be.`

**Comment by TraXIcoN** [comment]
Thanks for the update @achoudh5
I will add the required labels
